replicaCount: 2

image:
  repository: karthikeya2k24/ci-go-web-image
  tag: "<commit-sha>"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 1234

ingress:
  enabled: false
  host: mygoweb.app
