replicaCount: 2

image:
  repository: karthikeya2k24/my-go-web-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 1234

ingress:
  enabled: false
  host: mygoweb.app
